### ISSUE TITLE
Do you have a beta version compiled ?

### ISSUE THREAD

**Issue by mikhoul** [SophiaUI/SophiApp#1]
Hi,

Do you have a beta version compiled ?

Regards ! :octocat:

**Comment by farag2** [comment]
:)
https://youtu.be/2x_AfmCvfu4

These builds are for internal testing only. Buttons don't work. And don't support the English language despite the translation exists inside the code.

https://github.com/SophiaUI/SophiApp/releases

**Comment by farag2** [comment]
Wait until the summer. :)
